### ISSUE TITLE
Empezar el trabajo

### ISSUE THREAD

**Issue by dsm0028** [dsm0028/GESPRO_PracticaGestionTareas_1718#1]
Porque hay que empezar.

**Comment by mpc0082** [comment]
Estoy completamente de acuerdo con su aportación

**Comment by dsm0028** [comment]
muchas gracias compañero Marcos, en breve deberemos resolver esta situación.

**Comment by ubunanonandi** [comment]
Dado que ya hemos empezado, cerraremos esta tarea.

**Comment by dsm0028** [comment]
Es que no me queda claro este issue así que me gustaría reabrirlo otra vez para dar lugar a una serie de debates entre mis compañeros y yo. 
A mi parecer se han producido muchos desbarajustes durante este corto pero intenso recorrido y creo que deberíamos empezar todo el proyecto desde cero, eso desde luego.

**Comment by fao0006** [comment]
Te explico, resulta que tuvimos que empezar el trabajo y decidimos crear una tarea para empezar. Luego comenzamos el trabajo y por consiguiente, esta tarea se cerró. Y ahora explicado de nuevo, cierro la tarea otra vez.
