### ISSUE TITLE
Leer cap. 3 libro Android OpenCV

### ISSUE THREAD

**Issue by dsm0028** [dsm0028/GESPRO_PracticaGestionTareas_1718#16]
Chapter 3, Applying Image Effects, explores OpenCV's functionality to manipulate color channels and neighborhoods of pixels. The Apache Commons Math library is also introduced. We expand our app to include channel-mixing filters, "curve" filters, and a filter that darkens edges.

**Comment by fao0006** [comment]
Libro leído, perfecto.
