### ISSUE TITLE
Elección de repositorio

### ISSUE THREAD

**Issue by dcs0028** [dsm0028/GESPRO_PracticaGestionTareas_1718#2]
Herramientas consideradas:

    GitHub
    Bitbucket
    GitLab

Herramienta elegida:

    GitHub

GitHub es la plataforma web de hospedaje de repositorios por excelencia. Ofrece todas las funcionalidades de Git, revisión de código, documentación, bug tracking, gestión de tareas, wikis, red social... y numerosas integraciones con otros servicios.

Utilizaremos GitHub como plataforma principal donde hospedaremos el código del proyecto, la gestión de proyecto (gracias a ZenHub) y la documentación (gracias a sus wikis).

**Comment by dcs0028** [comment]
Debido a que estamos hablando por GitHub asumo que todo el mundo está de acuerdo con la elección.

**Comment by dsm0028** [comment]
Nunca está de más poner aquí la issue. Ayer me eocontré a @mpc0082 intentando subr código al teletexto.

**Comment by dcs0028** [comment]
El teletexto es engañoso, yo el otro día casi creé una IA intentando ver el resultado del Las Palmas-Celta

**Comment by dcs0028** [comment]
Me lo dijo la IA

**Comment by dsm0028** [comment]
Creo que empataron a 3. Ningún equipo se llevó los tres puntos, aunque fue un gran partido disputado en el Estadio Gran Canaria

**Comment by mpc0082** [comment]
> Nunca está de más poner aquí la issue. Ayer me encontré a @mpc0082 intentando subir código al teletexto.


La fuente usada en el teletexto me confundió

**Comment by dcs0028** [comment]
Ya elegido el repositorio, cierro esta tarea
