### ISSUE TITLE
Documentar sprints anteriores

### ISSUE THREAD

**Issue by fao0006** [dsm0028/GESPRO_PracticaGestionTareas_1718#33]
Empezar a documentar los sprints ya realizados.

**Comment by dcs0028** [comment]
Finalizada

**Comment by fao0006** [comment]
¿Hasta donde tenemos documentado?

**Comment by dcs0028** [comment]
¿Que os parece?

**Comment by dsm0028** [comment]
Este grado de documentación es apropiado. Propongo cerrarlo.

**Comment by fao0006** [comment]
Perfecto, procedo a cerrarlo ya que veo a todos de acuerdo.
