### ISSUE TITLE
Elegir IDE

### ISSUE THREAD

**Issue by dcs0028** [dsm0028/GESPRO_PracticaGestionTareas_1718#4]
Herramientas consideradas:

    Android Studio
    Eclipse

Herramienta elegida:

    Android Studio

Android Studio es el IDE oficial para el desarrollo de aplicaciones Android. Está basado en IntelliJ IDEA de JetBrains. Proporciona soporte para Gradle, emulador, editor de layouts, refactorizaciones específicas de Android, herramientas Lint para detectar problemas de rendimiento, uso, compatibilidad de versión, etc.

No se descarta el uso de algún otro IDE para la realización de prototipos fuera de la plataforma Android.

**Comment by dsm0028** [comment]
Mi tía Merche me ha recomendado el uso de Eclipse. Pero creo firmemente que android Studio es mejor para esta tarea.

**Comment by dcs0028** [comment]
Todo claro con la herramienta. Cierro
