### ISSUE TITLE
Documentar sprint 4

### ISSUE THREAD

**Issue by dsm0028** [dsm0028/GESPRO_PracticaGestionTareas_1718#46]

**Comment by dsm0028** [comment]
Esto es una práctica de control de la asignatura de Seguridad Informática del Segundo Semestre de la Universidad de Burgos, a ver parfavar donde dejamos abiertas nuestras cuentas que podría haber sido bastante más joputa. 

Saludos cordiales.

Atentamente,
Austricliniano Ali Vaporub.

**Comment by fao0006** [comment]
Hay que terminar el sprint 4 y después realizar esta tarea.

**Comment by dsm0028** [comment]
Suficiente.

**Comment by fao0006** [comment]
He documentado varias issues del sprint 4, ¿quedan algunas?

**Comment by mpc0082** [comment]
Los issues que me corresponden están documentados

**Comment by dsm0028** [comment]
Parece que está todo ya...

**Comment by dcs0028** [comment]
Mi parte está. el resto me parece correcto

**Comment by dsm0028** [comment]
Pues cerramos.
